[system]
compatible=%RAUC_COMPATIBLE%
bootloader=custom
max-bundle-download-size=209715200
mountprefix=/tmp/rauc
data-directory=/data/rauc

[handlers]
bootloader-custom-backend=/usr/lib/rauc/fwu_backend.sh

[keyring]
path=/etc/rauc/ca.cert.pem
use-bundle-signing-time=true

[slot.fip.0]
device=/dev/disk/by-partlabel/fip-a
type=raw
bootname=A

[slot.fip.1]
device=/dev/disk/by-partlabel/fip-b
type=raw
bootname=B

[slot.rootfs.0]
device=/dev/disk/by-partlabel/rootfs-a
type=raw
parent=fip.0

[slot.rootfs.1]
device=/dev/disk/by-partlabel/rootfs-b
type=raw
parent=fip.1
